blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts'))
]

posts/urls.py
from django.urls import path
from .views import index, get_post_view, create_post_view, delete_post

app_name = 'posts'
urlpatterns =[
    path('', index, name='index'),
    path('create-post/', create_post_view, name='create-post'),
    path('get-post/<str:pk>/', get_post_view, name='get-post'),
    path('delete-post', delete_post, name='delete-post'),
]

posts/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.CharField(max_length=1000000)
    created_at = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return f"title: {str(self.title[:15])}"

posts/views.py
from django.http.response import Http404
from django.shortcuts import render, redirect
from .models import Post
from django.http import HttpResponse

# Create your views here.
def index(request):
    posts = Post.objects.all()
    return render(request, 'index.html', {'posts':posts})

def get_post_view(request, pk):
    post = Post.objects.get(id=pk)
    return render(request, "detail.html", {"post":post})


def create_post_view(request):
    if request.method == 'POST':
        title = request.POST['title']
        body = request.POST['body']

        if title == "" or body == "":
            return render(request, 'create-post.html', {'invalid': True})
        else:
            post = Post.objects.create(title=title, body=body)
            post.save()
            return redirect('posts:index')
            
    return render(request, 'create-post.html')

def delete_post(request):
    id = request.POST.get('post-id')
    post = Post.objects.get(id=id)
    post.delete()
    return redirect('posts:index')

templates/base.html
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block titlepage %}{% endblock titlepage %}</title>
    <style>
        .pageTitle{
            padding-top: 15px;
            background-color: rgb(23, 27, 26);
            margin: 0 auto;
            height: 100px;
            width: 80%;
            padding-bottom: 10px;
            color: whitesmoke;
            padding-top: 20px;
            justify-content: center;
            text-align: center;
            border-radius: 5px;
        }

        .posts{
            background-color: rgb(220, 236, 231);
            margin: auto;
            margin-top: 20px;
            width: 80%;
            padding: 10px;
            margin-bottom: 10px;
        }
       
        .myForm{
            justify-content: center;
            text-align: center;
            margin: 0 auto;
            background-color: rgb(220, 236, 231);
            width: 50%;
            margin-top: 25px;
            margin-bottom: 20px;
            padding: 10px;
        }
        
    </style>
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

templates/create-post.html
{% extends 'base.html' %}
{% block title %}
    Add post
{% endblock title %}

{% block content %}
<div class="myForm">
    
    {% if invalid %}
      <div class="alert alert-danger" role="alert">
        Empty fields!
      </div>
    {% endif %}

    <h1>Add new Post</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" class="form-control" name='title' id='title-post' placeholder="Title">
        </div><br>
        <div class="form-group">
            <textarea name="body" class="form-control" id="body-post" cols="20" rows="10"></textarea>
        </div><br>
        <button type="submit" class="btn btn-primary">Add Post</button>
    </form>
</div>
{% endblock content %}

templates/detail.html
{% extends 'base.html' %}

{% block titlepage %}Post{% endblock titlepage %}

{% block content %}
    <div class='pageTitle'>
        <h1>TryBlog</h1>
    </div>
    
    <div class="posts">  
        <h3>{{post.title}}</h3>
        <h6>{{post.created_at}}</h6>
        <p>{{post.body}}</p>
    </div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block titlepage %}Try blog{% endblock titlepage %}

{% block content %}
<div class='pageTitle'><h1>Try Blog</h1></div>
 


<div class="mx-auto mt-4" style="width: 100px;">
    <a href="{% url 'posts:create-post' %}"><button class="btn btn-primary">Add Post</button></a>
  </div>

{%for post in posts reversed%}
    <div class="posts" style="color: black; text-decoration:none;">
        <h3>{{post.title}}</h3>
            <h6>{{post.created_at}}</h6>
            <p>{{post.body|truncatewords:20}}</p>
        <a href="get-post/{{post.id}}">
            <button class="btn btn-secondary">See post</button>
        </a>
        <form action="{% url 'posts:delete-post' %}" method="POST" class="mt-2">
            {% csrf_token %}
            <input type="hidden" name="post-id" value="{{post.id}}"/>
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </div>
{%endfor%}

{% endblock content %}

templates/post.html
{% extends 'base.html' %}

{% block titlepage %}Post{% endblock titlepage %}

{% block content %}
    <div class='pageTitle'>
        <h1>TryBlog</h1>
    </div>
    
    <div class="posts">  
        <h3>{{post.title}}</h3>
        <h6>{{post.created_at}}</h6>
        <p>{{post.body}}</p>
    </div>
{% endblock content %}